/**
 * ARGUS Report Generator
 *
 * Compiles all agent intelligence into a Palantir-style
 * classified intelligence assessment document (Markdown).
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { AuditReport, AGENTFramework } from '../types.js';
import { cleanSlopFromText } from './anti-slop.js';

export class ReportGenerator {
  generate(report: AuditReport, outputDir: string): string {
    mkdirSync(outputDir, { recursive: true });

    const md = cleanSlopFromText(this.render(report));
    const filename = `ARGUS-${report.metadata.targetOrg.replace(/\W+/g, '-')}-${
      new Date().toISOString().split('T')[0]
    }.md`;
    const outputPath = join(outputDir, filename);

    writeFileSync(outputPath, md, 'utf-8');
    return outputPath;
  }

  private render(r: AuditReport): string {
    const sections = [
      this.renderClassificationBanner(r),
      this.renderTitlePage(r),
      this.renderExecutiveSummary(r),
      this.renderOrgIntelligence(r),
      this.renderTechIntelligence(r),
      this.renderSecurityRisk(r),
      this.renderCompetitiveIntel(r),
      this.renderAIGovernance(r),
      this.renderAGENTFramework(r),
      this.renderRiskMatrix(r),
      this.renderStrategicRecommendations(r),
      this.renderMethodology(r),
      this.renderSourceAppendix(r),
      this.renderClassificationFooter(r),
    ];

    return sections.join('\n\n---\n\n');
  }

  private renderClassificationBanner(r: AuditReport): string {
    return [
      `> **${r.metadata.classification}** // ARGUS INTELLIGENCE PRODUCT`,
      `> Report ID: ${r.metadata.reportId}`,
      `> Generated: ${new Date(r.metadata.generatedAt).toUTCString()}`,
    ].join('\n');
  }

  private renderTitlePage(r: AuditReport): string {
    const m = r.metadata;
    return [
      `# ORGANIZATIONAL INTELLIGENCE ASSESSMENT`,
      `## ${r.orgIntelligence.name}`,
      '',
      '| Field | Value |',
      '|-------|-------|',
      `| **Target** | ${m.targetOrg} |`,
      `| **URL** | ${m.targetUrl} |`,
      `| **Report ID** | ${m.reportId} |`,
      `| **Classification** | ${m.classification} |`,
      `| **Date** | ${new Date(m.generatedAt).toLocaleDateString()} |`,
      `| **Audit Depth** | ${m.auditDepth} |`,
      `| **Agents Deployed** | ${m.agentCount} |`,
      `| **Research Queries** | ${m.researchQueries} |`,
      `| **Sources Collected** | ${r.allSources.length} |`,
      `| **Duration** | ${(m.totalDurationMs / 1000).toFixed(1)}s |`,
      `| **Generated By** | ${m.generatedBy} |`,
    ].join('\n');
  }

  private renderExecutiveSummary(r: AuditReport): string {
    return [
      '# EXECUTIVE SUMMARY',
      '',
      r.executiveSummary || '*Executive summary generation requires Claude API.*',
    ].join('\n');
  }

  private renderOrgIntelligence(r: AuditReport): string {
    const o = r.orgIntelligence;
    const lines = [
      '# 1. ORGANIZATIONAL INTELLIGENCE',
      '',
      '## 1.1 Organization Profile',
      '',
      '| Attribute | Intelligence |',
      '|-----------|-------------|',
      `| **Name** | ${o.name} |`,
      `| **Website** | ${o.website} |`,
      `| **Founded** | ${o.founded || 'Not determined'} |`,
      `| **Headquarters** | ${o.headquarters || 'Not determined'} |`,
      `| **CEO** | ${o.ceo || 'Not determined'} |`,
      `| **Employees** | ${o.employees || 'Not determined'} |`,
      `| **Revenue** | ${o.revenue || 'Not determined'} |`,
      `| **Industry** | ${o.industry || 'Not determined'} |`,
      `| **Public/Private** | ${o.publicOrPrivate || 'Not determined'} |`,
      `| **Stock Ticker** | ${o.stockTicker || 'N/A'} |`,
      '',
      '## 1.2 Overview',
      '',
      o.overview || '*Research data not available*',
    ];

    if (o.keyProducts.length > 0) {
      lines.push('', '## 1.3 Key Products & Services', '');
      for (const p of o.keyProducts) {
        lines.push(`- ${p}`);
      }
    }

    if (o.recentNews.length > 0) {
      lines.push('', '## 1.4 Recent Developments', '');
      for (const n of o.recentNews) {
        lines.push(`- ${n}`);
      }
    }

    return lines.join('\n');
  }

  private renderTechIntelligence(r: AuditReport): string {
    const t = r.techIntelligence;
    const lines = [
      '# 2. TECHNOLOGY INTELLIGENCE',
      '',
    ];

    if (t.techStack.length > 0) {
      lines.push('## 2.1 Technology Stack', '', '| Category | Technologies | Confidence |', '|----------|-------------|------------|');
      for (const s of t.techStack) {
        lines.push(`| ${s.category} | ${s.technologies.join(', ')} | ${s.confidence} |`);
      }
      lines.push('');
    }

    if (t.aiCapabilities.length > 0) {
      lines.push('## 2.2 AI & Machine Learning Capabilities', '', '| Capability | Maturity | Confidence | Description |', '|-----------|----------|------------|-------------|');
      for (const c of t.aiCapabilities) {
        lines.push(`| ${c.capability} | ${c.maturity} | ${c.confidence} | ${c.description.slice(0, 100)} |`);
      }
      lines.push('');
    }

    if (t.patents.length > 0) {
      lines.push('## 2.3 Patents & IP', '');
      for (const p of t.patents) {
        lines.push(`- **${p.year}**: ${p.title}`);
      }
      lines.push('');
    }

    if (t.engineeringCulture) {
      lines.push('## 2.4 Engineering Assessment', '', t.engineeringCulture, '');
    }

    if (t.openSourcePresence) {
      lines.push('## 2.5 Open Source Presence', '', t.openSourcePresence, '');
    }

    return lines.join('\n');
  }

  private renderSecurityRisk(r: AuditReport): string {
    const s = r.securityRisk;
    const riskEmoji = s.riskScore <= 30 ? '🟢' : s.riskScore <= 60 ? '🟡' : '🔴';

    const lines = [
      '# 3. SECURITY & RISK ASSESSMENT',
      '',
      `**Overall Risk Score: ${riskEmoji} ${s.riskScore}/100**`,
      '',
    ];

    if (s.complianceCertifications.length > 0) {
      lines.push('## 3.1 Compliance Certifications', '');
      for (const c of s.complianceCertifications) {
        lines.push(`- ✅ ${c}`);
      }
      lines.push('');
    }

    if (s.knownBreaches.length > 0) {
      lines.push('## 3.2 Known Security Incidents', '', '| Date | Description |', '|------|-------------|');
      for (const b of s.knownBreaches) {
        lines.push(`| ${b.date} | ${b.description.slice(0, 150)} |`);
      }
      lines.push('');
    } else {
      lines.push('## 3.2 Known Security Incidents', '', 'No significant breaches identified in open-source intelligence.', '');
    }

    if (s.regulatoryRisks.length > 0) {
      lines.push('## 3.3 Regulatory Risks', '');
      for (const rr of s.regulatoryRisks) {
        lines.push(`- ⚠️ ${rr}`);
      }
      lines.push('');
    }

    if (s.reputationRisks.length > 0) {
      lines.push('## 3.4 Reputation Risks', '');
      for (const rr of s.reputationRisks) {
        lines.push(`- ${rr}`);
      }
      lines.push('');
    }

    if (s.privacyPolicySummary) {
      lines.push('## 3.5 Privacy & Data Handling', '', s.privacyPolicySummary, '');
    }

    if (s.overallPosture) {
      lines.push('## 3.6 Detailed Assessment', '', s.overallPosture, '');
    }

    return lines.join('\n');
  }

  private renderCompetitiveIntel(r: AuditReport): string {
    const c = r.competitiveIntel;
    const lines = [
      '# 4. COMPETITIVE INTELLIGENCE',
      '',
    ];

    if (c.competitors.length > 0) {
      lines.push('## 4.1 Competitive Landscape', '', '| Competitor | Threat Level | Comparison |', '|-----------|-------------|------------|');
      for (const comp of c.competitors) {
        lines.push(`| ${comp.name} | ${comp.threatLevel} | ${comp.comparison.slice(0, 100)} |`);
      }
      lines.push('');
    }

    if (c.differentiators.length > 0) {
      lines.push('## 4.2 Competitive Differentiators', '');
      for (const d of c.differentiators) {
        lines.push(`- 💪 ${d}`);
      }
      lines.push('');
    }

    if (c.weaknesses.length > 0) {
      lines.push('## 4.3 Identified Vulnerabilities', '');
      for (const w of c.weaknesses) {
        lines.push(`- ⚡ ${w}`);
      }
      lines.push('');
    }

    if (c.partnerships.length > 0) {
      lines.push('## 4.4 Strategic Partnerships', '');
      for (const p of c.partnerships) {
        lines.push(`- **${p.partner}**: ${p.nature}`);
      }
      lines.push('');
    }

    if (c.fundingHistory) {
      lines.push('## 4.5 Funding & Growth', '', c.fundingHistory, '');
    }

    if (c.marketPosition) {
      lines.push('## 4.6 Market Position Analysis', '', c.marketPosition, '');
    }

    return lines.join('\n');
  }

  private renderAIGovernance(r: AuditReport): string {
    if (!r.aiGovernance) return '';
    const g = r.aiGovernance;
    const lines = [
      '# 5. AI GOVERNANCE & OPERATIONAL READINESS',
      '',
    ];

    if (g.currentMaturity) {
      lines.push('## 5.1 AI Maturity Assessment', '', g.currentMaturity.slice(0, 1500), '');
    }

    if (g.governancePolicies) {
      lines.push('## 5.2 Governance Policies & Frameworks', '', g.governancePolicies, '');
    }

    if (g.bestPractices.length > 0) {
      lines.push('## 5.3 AI Best Practices Adopted', '');
      for (const bp of g.bestPractices) lines.push(`- ${bp}`);
      lines.push('');
    }

    if (g.aiUseCases.length > 0) {
      lines.push('## 5.4 AI Use Cases & Adoption', '', '| Use Case | Domain | Maturity | Description |', '|----------|--------|----------|-------------|');
      for (const uc of g.aiUseCases) {
        lines.push(`| ${uc.name} | ${uc.domain} | ${uc.maturity} | ${uc.description.slice(0, 80)} |`);
      }
      lines.push('');
    }

    if (g.adoptionApproach) {
      lines.push('## 5.5 AI Operational Strategy', '', g.adoptionApproach.slice(0, 1500), '');
    }

    if (g.operationalReadiness) {
      lines.push('## 5.6 Operational Readiness', '', g.operationalReadiness, '');
    }

    return lines.join('\n');
  }

  private renderAGENTFramework(r: AuditReport): string {
    if (!r.aiGovernance?.agentFramework) return '';
    const af = r.aiGovernance.agentFramework;
    if (af.audit.steps.length === 0 && !af.executiveSummary) return '';

    const lines = [
      '# 6. AGENT FRAMEWORK — Agentic AI Workflow Transformation',
      '',
      '*Based on the Harvard Agentic AI AGENT Framework: Audit, Gauge, Engineer, Navigate, Track*',
      '',
    ];

    // Audit Phase
    lines.push('## 6.1 AUDIT Phase: Current Workflow', '');
    lines.push(`**Workflow:** ${af.audit.workflowName}`, '');
    lines.push(`**Trigger:** ${af.audit.trigger}`, '');

    for (let i = 0; i < af.audit.steps.length; i++) {
      const s = af.audit.steps[i];
      lines.push(`### Step ${i + 1}: ${s.name}`, '');
      lines.push(`- **Overview:** ${s.overview}`);
      lines.push(`- **Objective:** ${s.objective}`);
      lines.push(`- **Roles:** ${s.roles}`);
      lines.push(`- **Data:** ${s.data}`);
      lines.push(`- **Systems:** ${s.systems}`);
      lines.push(`- **Output:** ${s.output}`, '');
    }

    lines.push(`**Final Output:** ${af.audit.finalOutput}`, '');

    // Gauge Phase
    lines.push('## 6.2 GAUGE Phase: Workflow Assessment', '');
    lines.push(`**Expected Outcome:** ${af.gauge.expectedOutcome}`, '');

    if (af.gauge.assessments.length > 0) {
      lines.push('| Step | Impact | Repeatability | Complexity | Notes |', '|------|--------|--------------|------------|-------|');
      for (const a of af.gauge.assessments) {
        lines.push(`| ${a.stepName} | ${a.impactScore}/5 | ${a.repeatabilityScore}/5 | ${a.complexityScore}/5 | ${a.notes.slice(0, 60)} |`);
      }
      lines.push('');
    }

    // Engineer Phase
    lines.push('## 6.3 ENGINEER Phase: Agent-First Workflow Redesign', '');

    if (af.engineer.redesignMap.length > 0) {
      lines.push('### Redesign Map', '', '| Step | Agent Action | Human Action | Rationale |', '|------|-------------|-------------|-----------|');
      for (const rm of af.engineer.redesignMap) {
        lines.push(`| ${rm.stepName} | ${rm.agentAction ? 'Yes' : 'No'} | ${rm.humanAction ? 'Yes' : 'No'} | ${rm.rationale.slice(0, 80)} |`);
      }
      lines.push('');
    }

    if (af.engineer.challenges.length > 0) {
      lines.push('### Challenges & Agent Solutions', '', '| Step | Challenge | Agent Solution |', '|------|-----------|----------------|');
      for (const c of af.engineer.challenges) {
        lines.push(`| ${c.stepName} | ${c.challenge.slice(0, 60)} | ${c.agentSolution.slice(0, 60)} |`);
      }
      lines.push('');
    }

    const pr = af.engineer.processRefactoring;
    if (pr.blockers.length > 0) {
      lines.push('### Process Refactoring', '');
      lines.push('**Current Blockers:**');
      for (const b of pr.blockers) lines.push(`- ${b}`);
      lines.push('', '**Removal Strategies:**');
      for (const s of pr.removalStrategies) lines.push(`- ${s}`);
      lines.push('');
    }

    const ds = af.engineer.designSpecs;
    if (ds.agentRoles) {
      lines.push('### Design Specifications', '');
      lines.push(`- **Agent Roles:** ${ds.agentRoles}`);
      lines.push(`- **Orchestration:** ${ds.orchestrationArchitecture}`);
      lines.push(`- **Key Inputs:** ${ds.keyInputs}`);
      lines.push(`- **Actions/Tools:** ${ds.actions}`);
      lines.push(`- **Outputs:** ${ds.outputs}`, '');
    }

    // Navigate Phase
    lines.push('## 6.4 NAVIGATE Phase: Human-Agent Collaboration', '');

    if (af.navigate.interactions.length > 0) {
      lines.push('| Step | Human Role | Agent Role | Interaction |', '|------|-----------|------------|-------------|');
      for (const i of af.navigate.interactions) {
        lines.push(`| ${i.stepName} | ${i.humanRole.slice(0, 40)} | ${i.agentRole.slice(0, 40)} | ${i.interactionType.slice(0, 40)} |`);
      }
      lines.push('');
    }

    if (af.navigate.transparency) lines.push(`**Transparency:** ${af.navigate.transparency}`, '');
    if (af.navigate.governance) lines.push(`**Governance:** ${af.navigate.governance}`, '');
    if (af.navigate.roleRedefinition) lines.push(`**Role Redefinition:** ${af.navigate.roleRedefinition}`, '');
    if (af.navigate.trainingNeeds) lines.push(`**Training:** ${af.navigate.trainingNeeds}`, '');

    // Track Phase
    lines.push('## 6.5 TRACK Phase: Value Measurement', '');
    if (af.track.desiredOutcome) lines.push(`**Desired Outcome:** ${af.track.desiredOutcome}`, '');

    if (af.track.successSignals.length > 0) {
      lines.push('**Success Signals:**');
      for (const s of af.track.successSignals) lines.push(`- ${s}`);
      lines.push('');
    }

    if (af.track.metrics.length > 0) {
      lines.push('**Metrics:**');
      for (const m of af.track.metrics) lines.push(`- ${m}`);
      lines.push('');
    }

    // Executive Summary
    if (af.executiveSummary) {
      lines.push('## 6.6 AGENT Framework Executive Summary', '', af.executiveSummary, '');
    }

    return lines.join('\n');
  }

  private renderRiskMatrix(r: AuditReport): string {
    if (r.riskMatrix.length === 0) return '';

    const lines = [
      '# 7. RISK MATRIX',
      '',
      '| Category | Risk | Likelihood | Impact | Score | Level |',
      '|----------|------|-----------|--------|-------|-------|',
    ];

    for (const rm of r.riskMatrix) {
      const emoji = rm.threatLevel === 'CRITICAL' ? '🔴' : rm.threatLevel === 'HIGH' ? '🟠' : rm.threatLevel === 'MEDIUM' ? '🟡' : '🟢';
      lines.push(`| ${rm.category} | ${rm.riskName} | ${rm.likelihood}/10 | ${rm.impact}/10 | ${rm.riskScore} | ${emoji} ${rm.threatLevel} |`);
    }

    return lines.join('\n');
  }

  private renderStrategicRecommendations(r: AuditReport): string {
    return [
      '# 8. STRATEGIC RECOMMENDATIONS',
      '',
      r.strategicRecommendations.length > 0
        ? r.strategicRecommendations.map((rec, i) =>
            `### ${i + 1}. [${rec.priority}] ${rec.title}\n${rec.description}\n- **Effort**: ${rec.effort} | **Impact**: ${rec.impact}\n- **Rationale**: ${rec.rationale}`
          ).join('\n\n')
        : '*Strategic recommendations included in executive summary above.*',
    ].join('\n');
  }

  private renderMethodology(r: AuditReport): string {
    return ['# 9. METHODOLOGY', '', r.methodology].join('\n');
  }

  private renderSourceAppendix(r: AuditReport): string {
    const lines = [
      '# APPENDIX A: SOURCES',
      '',
      `Total sources consulted: ${r.allSources.length}`,
      '',
    ];

    for (let i = 0; i < r.allSources.length; i++) {
      lines.push(`${i + 1}. ${r.allSources[i]}`);
    }

    return lines.join('\n');
  }

  private renderClassificationFooter(r: AuditReport): string {
    return [
      '---',
      '',
      `> **${r.metadata.classification}** // ARGUS INTELLIGENCE PRODUCT`,
      `> This report was generated by automated OSINT collection and analysis.`,
      `> All information is derived from publicly available sources.`,
      `> Verify critical findings with primary sources before decision-making.`,
      `> ${r.metadata.generatedBy}`,
    ].join('\n');
  }
}
