/**
 * ARGUS Report Generator
 *
 * Compiles all agent intelligence into a Palantir-style
 * classified intelligence assessment document (Markdown).
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { AuditReport } from '../types.js';

export class ReportGenerator {
  generate(report: AuditReport, outputDir: string): string {
    mkdirSync(outputDir, { recursive: true });

    const md = this.render(report);
    const filename = `ARGUS-${report.metadata.targetOrg.replace(/\W+/g, '-')}-${
      new Date().toISOString().split('T')[0]
    }.md`;
    const outputPath = join(outputDir, filename);

    writeFileSync(outputPath, md, 'utf-8');
    return outputPath;
  }

  private render(r: AuditReport): string {
    const sections = [
      this.renderClassificationBanner(r),
      this.renderTitlePage(r),
      this.renderExecutiveSummary(r),
      this.renderOrgIntelligence(r),
      this.renderTechIntelligence(r),
      this.renderSecurityRisk(r),
      this.renderCompetitiveIntel(r),
      this.renderRiskMatrix(r),
      this.renderStrategicRecommendations(r),
      this.renderMethodology(r),
      this.renderSourceAppendix(r),
      this.renderClassificationFooter(r),
    ];

    return sections.join('\n\n---\n\n');
  }

  private renderClassificationBanner(r: AuditReport): string {
    return [
      `> **${r.metadata.classification}** // ARGUS INTELLIGENCE PRODUCT`,
      `> Report ID: ${r.metadata.reportId}`,
      `> Generated: ${new Date(r.metadata.generatedAt).toUTCString()}`,
    ].join('\n');
  }

  private renderTitlePage(r: AuditReport): string {
    const m = r.metadata;
    return [
      `# ORGANIZATIONAL INTELLIGENCE ASSESSMENT`,
      `## ${r.orgIntelligence.name}`,
      '',
      '| Field | Value |',
      '|-------|-------|',
      `| **Target** | ${m.targetOrg} |`,
      `| **URL** | ${m.targetUrl} |`,
      `| **Report ID** | ${m.reportId} |`,
      `| **Classification** | ${m.classification} |`,
      `| **Date** | ${new Date(m.generatedAt).toLocaleDateString()} |`,
      `| **Audit Depth** | ${m.auditDepth} |`,
      `| **Agents Deployed** | ${m.agentCount} |`,
      `| **Research Queries** | ${m.researchQueries} |`,
      `| **Sources Collected** | ${r.allSources.length} |`,
      `| **Duration** | ${(m.totalDurationMs / 1000).toFixed(1)}s |`,
      `| **Generated By** | ${m.generatedBy} |`,
    ].join('\n');
  }

  private renderExecutiveSummary(r: AuditReport): string {
    return [
      '# EXECUTIVE SUMMARY',
      '',
      r.executiveSummary || '*Executive summary generation requires Claude API.*',
    ].join('\n');
  }

  private renderOrgIntelligence(r: AuditReport): string {
    const o = r.orgIntelligence;
    const lines = [
      '# 1. ORGANIZATIONAL INTELLIGENCE',
      '',
      '## 1.1 Organization Profile',
      '',
      '| Attribute | Intelligence |',
      '|-----------|-------------|',
      `| **Name** | ${o.name} |`,
      `| **Website** | ${o.website} |`,
      `| **Founded** | ${o.founded || 'Not determined'} |`,
      `| **Headquarters** | ${o.headquarters || 'Not determined'} |`,
      `| **CEO** | ${o.ceo || 'Not determined'} |`,
      `| **Employees** | ${o.employees || 'Not determined'} |`,
      `| **Revenue** | ${o.revenue || 'Not determined'} |`,
      `| **Industry** | ${o.industry || 'Not determined'} |`,
      `| **Public/Private** | ${o.publicOrPrivate || 'Not determined'} |`,
      `| **Stock Ticker** | ${o.stockTicker || 'N/A'} |`,
      '',
      '## 1.2 Overview',
      '',
      o.overview || '*Research data not available*',
    ];

    if (o.keyProducts.length > 0) {
      lines.push('', '## 1.3 Key Products & Services', '');
      for (const p of o.keyProducts) {
        lines.push(`- ${p}`);
      }
    }

    if (o.recentNews.length > 0) {
      lines.push('', '## 1.4 Recent Developments', '');
      for (const n of o.recentNews) {
        lines.push(`- ${n}`);
      }
    }

    return lines.join('\n');
  }

  private renderTechIntelligence(r: AuditReport): string {
    const t = r.techIntelligence;
    const lines = [
      '# 2. TECHNOLOGY INTELLIGENCE',
      '',
    ];

    if (t.techStack.length > 0) {
      lines.push('## 2.1 Technology Stack', '', '| Category | Technologies | Confidence |', '|----------|-------------|------------|');
      for (const s of t.techStack) {
        lines.push(`| ${s.category} | ${s.technologies.join(', ')} | ${s.confidence} |`);
      }
      lines.push('');
    }

    if (t.aiCapabilities.length > 0) {
      lines.push('## 2.2 AI & Machine Learning Capabilities', '', '| Capability | Maturity | Confidence | Description |', '|-----------|----------|------------|-------------|');
      for (const c of t.aiCapabilities) {
        lines.push(`| ${c.capability} | ${c.maturity} | ${c.confidence} | ${c.description.slice(0, 100)} |`);
      }
      lines.push('');
    }

    if (t.patents.length > 0) {
      lines.push('## 2.3 Patents & IP', '');
      for (const p of t.patents) {
        lines.push(`- **${p.year}**: ${p.title}`);
      }
      lines.push('');
    }

    if (t.engineeringCulture) {
      lines.push('## 2.4 Engineering Assessment', '', t.engineeringCulture, '');
    }

    if (t.openSourcePresence) {
      lines.push('## 2.5 Open Source Presence', '', t.openSourcePresence, '');
    }

    return lines.join('\n');
  }

  private renderSecurityRisk(r: AuditReport): string {
    const s = r.securityRisk;
    const riskEmoji = s.riskScore <= 30 ? '🟢' : s.riskScore <= 60 ? '🟡' : '🔴';

    const lines = [
      '# 3. SECURITY & RISK ASSESSMENT',
      '',
      `**Overall Risk Score: ${riskEmoji} ${s.riskScore}/100**`,
      '',
    ];

    if (s.complianceCertifications.length > 0) {
      lines.push('## 3.1 Compliance Certifications', '');
      for (const c of s.complianceCertifications) {
        lines.push(`- ✅ ${c}`);
      }
      lines.push('');
    }

    if (s.knownBreaches.length > 0) {
      lines.push('## 3.2 Known Security Incidents', '', '| Date | Description |', '|------|-------------|');
      for (const b of s.knownBreaches) {
        lines.push(`| ${b.date} | ${b.description.slice(0, 150)} |`);
      }
      lines.push('');
    } else {
      lines.push('## 3.2 Known Security Incidents', '', 'No significant breaches identified in open-source intelligence.', '');
    }

    if (s.regulatoryRisks.length > 0) {
      lines.push('## 3.3 Regulatory Risks', '');
      for (const rr of s.regulatoryRisks) {
        lines.push(`- ⚠️ ${rr}`);
      }
      lines.push('');
    }

    if (s.reputationRisks.length > 0) {
      lines.push('## 3.4 Reputation Risks', '');
      for (const rr of s.reputationRisks) {
        lines.push(`- ${rr}`);
      }
      lines.push('');
    }

    if (s.privacyPolicySummary) {
      lines.push('## 3.5 Privacy & Data Handling', '', s.privacyPolicySummary, '');
    }

    if (s.overallPosture) {
      lines.push('## 3.6 Detailed Assessment', '', s.overallPosture, '');
    }

    return lines.join('\n');
  }

  private renderCompetitiveIntel(r: AuditReport): string {
    const c = r.competitiveIntel;
    const lines = [
      '# 4. COMPETITIVE INTELLIGENCE',
      '',
    ];

    if (c.competitors.length > 0) {
      lines.push('## 4.1 Competitive Landscape', '', '| Competitor | Threat Level | Comparison |', '|-----------|-------------|------------|');
      for (const comp of c.competitors) {
        lines.push(`| ${comp.name} | ${comp.threatLevel} | ${comp.comparison.slice(0, 100)} |`);
      }
      lines.push('');
    }

    if (c.differentiators.length > 0) {
      lines.push('## 4.2 Competitive Differentiators', '');
      for (const d of c.differentiators) {
        lines.push(`- 💪 ${d}`);
      }
      lines.push('');
    }

    if (c.weaknesses.length > 0) {
      lines.push('## 4.3 Identified Vulnerabilities', '');
      for (const w of c.weaknesses) {
        lines.push(`- ⚡ ${w}`);
      }
      lines.push('');
    }

    if (c.partnerships.length > 0) {
      lines.push('## 4.4 Strategic Partnerships', '');
      for (const p of c.partnerships) {
        lines.push(`- **${p.partner}**: ${p.nature}`);
      }
      lines.push('');
    }

    if (c.fundingHistory) {
      lines.push('## 4.5 Funding & Growth', '', c.fundingHistory, '');
    }

    if (c.marketPosition) {
      lines.push('## 4.6 Market Position Analysis', '', c.marketPosition, '');
    }

    return lines.join('\n');
  }

  private renderRiskMatrix(r: AuditReport): string {
    if (r.riskMatrix.length === 0) return '';

    const lines = [
      '# 5. RISK MATRIX',
      '',
      '| Category | Risk | Likelihood | Impact | Score | Level |',
      '|----------|------|-----------|--------|-------|-------|',
    ];

    for (const rm of r.riskMatrix) {
      const emoji = rm.threatLevel === 'CRITICAL' ? '🔴' : rm.threatLevel === 'HIGH' ? '🟠' : rm.threatLevel === 'MEDIUM' ? '🟡' : '🟢';
      lines.push(`| ${rm.category} | ${rm.riskName} | ${rm.likelihood}/10 | ${rm.impact}/10 | ${rm.riskScore} | ${emoji} ${rm.threatLevel} |`);
    }

    return lines.join('\n');
  }

  private renderStrategicRecommendations(r: AuditReport): string {
    return [
      '# 6. STRATEGIC RECOMMENDATIONS',
      '',
      r.strategicRecommendations.length > 0
        ? r.strategicRecommendations.map((rec, i) =>
            `### ${i + 1}. [${rec.priority}] ${rec.title}\n${rec.description}\n- **Effort**: ${rec.effort} | **Impact**: ${rec.impact}\n- **Rationale**: ${rec.rationale}`
          ).join('\n\n')
        : '*Strategic recommendations included in executive summary above.*',
    ].join('\n');
  }

  private renderMethodology(r: AuditReport): string {
    return ['# 7. METHODOLOGY', '', r.methodology].join('\n');
  }

  private renderSourceAppendix(r: AuditReport): string {
    const lines = [
      '# APPENDIX A: SOURCES',
      '',
      `Total sources consulted: ${r.allSources.length}`,
      '',
    ];

    for (let i = 0; i < r.allSources.length; i++) {
      lines.push(`${i + 1}. ${r.allSources[i]}`);
    }

    return lines.join('\n');
  }

  private renderClassificationFooter(r: AuditReport): string {
    return [
      '---',
      '',
      `> **${r.metadata.classification}** // ARGUS INTELLIGENCE PRODUCT`,
      `> This report was generated by automated OSINT collection and analysis.`,
      `> All information is derived from publicly available sources.`,
      `> Verify critical findings with primary sources before decision-making.`,
      `> ${r.metadata.generatedBy}`,
    ].join('\n');
  }
}
